# Generated by Django 2.2.4 on 2021-03-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
