# Generated by Django 2.2.4 on 2021-03-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0002_ninja_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
