# Generated by Django 2.2.4 on 2021-03-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0004_auto_20210319_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo',
            new_name='dojo_ID',
        ),
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='old dojo', max_length=250),
        ),
    ]
