# Generated by Django 2.2.4 on 2021-03-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0005_auto_20210319_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='age',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='state',
        ),
    ]
