# Generated by Django 2.2.4 on 2021-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads_app', '0002_auto_20210325_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(default='AndroidBot', max_length=100),
            preserve_default=False,
        ),
    ]
