# Generated by Django 2.2.4 on 2021-03-26 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads_app', '0003_book_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='person',
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='reads_app.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reads_app.User'),
            preserve_default=False,
        ),
    ]
