# Generated by Django 2.2.4 on 2021-03-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads_app', '0004_auto_20210326_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='users',
        ),
    ]
