# Generated by Django 2.2.4 on 2021-03-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_ORM_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
