# Generated by Django 2.2.4 on 2021-03-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='text',
            field=models.CharField(default='wrote a bunch of books', max_length=250),
        ),
    ]
