# Generated by Django 2.2.4 on 2021-03-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_app', '0002_author_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='authors_app.Book'),
        ),
    ]
